variables:
  packageVersion: '1.0.$(Build.BuildId)'

steps:
- task: UniversalPackages@0
  displayName: Publish Universal Package
  inputs:
    command: publish
    publishDirectory: '$(Build.ArtifactStagingDirectory)'
    vstsFeedPublish: 'Project1/newfeed'
    vstsFeedPackagePublish: 'cloudnautic-tools'
    versionOption: custom
    versionPublish: '$(packageVersion)'
    packagePublishDescription: 'Published using Azure Pipeline'

- task: UniversalPackages@0
  displayName: Download Universal Package
  inputs:
    command: download
    vstsFeed: 'Project1/newfeed'
    vstsFeedPackage: 'cloudnautic-tools'
    vstsFeedVersion: '$(packageVersion)'
    downloadDirectory: '$(Build.ArtifactStagingDirectory)/downloaded'
